### ISSUE TITLE
Journal Export Hammy Additions

### ISSUE THREAD

**Issue by winka826** [mary0L/Hustle-Hamster#40]
Get hammy to say Journal has been exported- so user knows.

Maybe get Hammy to print out the path of where it was saved. (Could be added to saved)

**Comment by winka826** [comment]
"This Journal has been saved to your device! If you need help finding your files check out the help page!"

**Comment by arcfernandes04** [comment]
This will be handled in `journalExport` all that `dailyLog` will need to do is call this method.
