### ISSUE TITLE
Implement dialogue skip key

### ISSUE THREAD

**Issue by mary0L** [mary0L/Hustle-Hamster#73]
User wished to be able to skip certain dialogue especially when there was a lot to read (due to reading speed). 

Should add a key-bind(?) for skipping the dialogue if wanted.

**Comment by winka826** [comment]
I'm not sure if a key press would work since we turn off the keyboard... however, I could add a function that allows the user to turn off hammy typing and print without waiting. It will have to be enabled every time they use the app, but I think this is the easiest implementation of this.
